image: ruby:2.3

variables:
  JEKYLL_ENV: production

before_script:
  ##
  ## Update apt-get
  ##
  - apt-get update -y

  ##
  ## Install ssh-agent if not already installed, it is required by Docker.
  ##
  - 'which ssh-agent || apt-get install openssh-client -y'

  ##
  ## Run ssh-agent (inside the build environment)
  ##
  - eval $(ssh-agent -s)

  ##
  ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  ## We're using tr to fix line endings which makes ed25519 keys work
  ## without extra base64 encoding.
  ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
  ##
  # - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 --decode) > /dev/null

  ##
  ## Create the SSH directory and give it the right permissions
  ##
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  ##
  ## Assuming you created the SSH_KNOWN_HOSTS variable, uncomment the
  ## following two lines.
  ##
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

  ##
  ## install nodejs
  ##
  - apt-get install -y -qq nodejs

  ##
  ## Install rsync if not already installed, it is required by Docker.
  ##
  - 'which rsync || apt-get install rsync -y'

  ##
  ## bundle install
  ##
  - bundle install

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

build:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master

deploy_review:
  stage: deploy
  script:
    - echo "Deploy a review"
    - bundle exec jekyll build -d review
    - ssh $SSH_USERNAME@filsinger.me 'mkdir -p public/filsinger.me/review/$CI_ENVIRONMENT_SLUG'
    - rsync -r review/* $SSH_USERNAME@filsinger.me:public/filsinger.me/review/$CI_ENVIRONMENT_SLUG
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://staging.filsinger.me/review/$CI_ENVIRONMENT_SLUG/
  only:
    - branches
  except:
    - master

deploy_production:
  stage: deploy
  script:
    - echo "Deploy to production server"
    - bundle exec jekyll build -d production
    - ssh $SSH_USERNAME@filsinger.me 'mkdir -p public/filsinger.me/production'
    - rsync -r production/* $SSH_USERNAME@filsinger.me:public/filsinger.me/production
  environment:
    name: production
    url: https://filsinger.me
  when: manual
  only:
  - master

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
    - bundle exec jekyll build -d staging
    - ssh $SSH_USERNAME@filsinger.me 'mkdir -p public/filsinger.me/staging'
    - rsync -r staging/* $SSH_USERNAME@filsinger.me:public/filsinger.me/staging
  environment:
    name: staging
    url: https://staging.filsinger.me
  only:
  - master
