markdown: kramdown
permalink: /:categories/:title/
lsi: true
compression: true
encoding: utf-8
author: filsinger
title: filsinger.me
utl: filsinger.me
description: Jason Filsinger's Website
github_username: filsinger
mastodon:
- username: filsinger
  instance: mastodon.social
        
kramdown:
  input: GFM
  syntax_highlighter: rouge

assets:
  compress:
    css:  sass
    js:   uglifier

sass:
  style: compressed

caching:
  path: ".jekyll-cache/assets"
  type: file # Possible values: memory, file
  enabled: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-categories

defaults:
  -
    scope:
      path:            "errormessages/"
    values:
      sitemap:         false
