source 'https://rubygems.org'

gem "classifier-reborn", "~> 2.3"
gem "jekyll", "~> 4.3"
gem "jekyll-categories", "~> 0.0.2"
gem "jekyll-feed", "~> 0.15.1"
gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-sitemap", "~> 1.4"
gem "kramdown", "~> 2.3"
gem "kramdown-parser-gfm", "~> 1.1"
gem "minima", "~> 2.5"
gem "rdiscount", "~> 2.2"
gem "rouge", "~> 3.26"
gem "safe_yaml", "~> 1.0"
gem "sass", "~> 3.7"
gem "uglifier", "~> 4.2"
gem "webrick", "~> 1.8"
