source 'https://rubygems.org'

gem 'classifier-reborn'
gem 'jekyll'
gem 'jekyll-assets'
gem 'jekyll-categories'
gem 'jekyll-feed'
gem 'rdiscount'
gem 'rouge'
gem 'kramdown'
gem 'safe_yaml'
gem 'sass'
gem 'uglifier'
